### ISSUE TITLE
(Feature Request) Multiple Yahoo Leagues

### ISSUE THREAD

**Issue by ebar03** [yahoo-fantasy/nfl-fantasy-football#10]
Is it possible to run this code for multiple leagues?

The only workaround I got it to save the repository multiple times, one for each Yahoo league and run it manually.

Could a feature be added to include additional leagues?

**Comment by bbenbenek** [comment]
You could put the entire script in a for-loop to loop through your different league IDs. Would just have to make the final directory it writes to dynamic as well to save to a new folder for each league. Something like that would work.
