### ISSUE TITLE
fantasy_stats.py - Errors when running this after following all steps.

### ISSUE THREAD

**Issue by Rahulc19** [yahoo-fantasy/nfl-fantasy-football#14]
Hi,

Beginner programmer here! I followed all the steps but am encountering these errors when I run fanasy_stats.py. For reference I am doing this for my NBA fantasy league. I attached a screenshot that show the errors.

Thanks
![python errors](https://user-images.githubusercontent.com/94762851/143149707-edd54c35-8f02-43ef-ac6e-6b5b5b7cbabf.png)

**Comment by bbenbenek** [comment]
['fantasy_content'] doesn't exist in the response json, which is why it's throwing that error. You can pinpoint it by going into the code and printing the actual response to see what it needs to be changed to. Yahoo will change the API sometimes, and i don't know if it's the same for Basketball
