### ISSUE TITLE
Trouble getting superflex position output from Data Transformations.py

### ISSUE THREAD

**Issue by ghost** [yahoo-fantasy/nfl-fantasy-football#16]
Apologies if this is the wrong place, but it seems I'm unable to pull data into the 'Data Transformations.py' from the superflex position in my league. I've tried a number of different inputs such as "Q/W/R/T' or as Yahoo displays it 'Q/W\nR/T'. The output .csv has the position totally blank. Any assistance here would be appreciated.

**Comment by ghost** [comment]
solved the issue by adding:

```
elif roster_position == 'Q/W/R/T':
    df_team.loc['Q/W/R/T'] = player_full_stats
    df_manager_team.loc['Q/W/R/T'] = pd.Series({'manager_name': full_name}) # contains managers name and the players full name
    df_points.loc['Q/W/R/T'] = pd.Series({'player_points': player_points})
    # Master list of players and Scores
    df_players.loc['Q/W/R/T'] = pd.Series({'player_key': player_key})
```

around line 195 in `Data Transformations.py`

**Comment by bbenbenek** [comment]
Thanks, I added it in!
