### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by jkuznetsky1230** [yahoo-fantasy/nfl-fantasy-football#3]
When I run the data transformation file, I am getting the following error:

raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value

Any ideas on work arounds?

**Comment by yahoo-fantasy** [comment]
Not sure exactly where you're getting that error. I did however just committed a bunch of updates. Try again and see if it works for you.
