### ISSUE TITLE
KeyError in Data_Transformations.py

### ISSUE THREAD

**Issue by megacorvega** [yahoo-fantasy/nfl-fantasy-football#4]
Hey all,

After running the Data_Transformations.py I'm getting:

`Week 1: Team: 1 Traceback (most recent call last):
  File "X:\PYTHON\projects\nfl-fantasy-football-master\Data Analysis\Data_Transformations.py", line 120, in <module>
    player_points = float(player_points_json['fantasy_content']['league'][1]['players']['0']['player'][1]['player_points']['total'])
KeyError: 'fantasy_content'`

`X:\PYTHON\projects\nfl-fantasy-football-master\Data Analysis>pause
Press any key to continue . . .`

Any ideas?

**Comment by yahoo-fantasy** [comment]
This should be resolved. I had my own personal League ID hard coded in the data transformations. This should now be automatic if you update the new league_info_form.txt with your League ID.
