### ISSUE TITLE
IR spot

### ISSUE THREAD

**Issue by KBM1111** [yahoo-fantasy/nfl-fantasy-football#5]
This doesn't pull in data if a player is in the IR spot and updating the league info form doesn't fix the problem.  There's an issue within the Data Transformation because the code isn't written for it.  Might be something to add for completeness.

**Comment by jamesgbrooks** [comment]
+1

**Comment by bbenbenek** [comment]
> +1

@jamesgbrooks can you supply an error that you're getting if you put "IR" in the 'league_info_form.txt'? You can run an API call  to get your settings to make sure the IR is there or if it's something different. I can't replicate it at the moment. If I add in "IR" I get a new row with an "IR" label in the weekly rosters folder after running the Data Transformations script.

```
url = 'https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.XXXXXX/settings'
response = oauth.session.get(url, params={'format': 'json'})
r = response.json()
```
