### ISSUE TITLE
Invalid Argument in Data_Transformations.py

### ISSUE THREAD

**Issue by Hargobind-K** [yahoo-fantasy/nfl-fantasy-football#9]
Hey all!

Sorry if this question is naive of me, I'm in the very nascent stages of learning python. 

The error I'm running into is in the Data_Transformations.py file I get this error when running the file:

```
In: runfile('C:/Users/hk/Desktop/FF/nfl-fantasy-football-master/Data Analysis/Data Transformations.py', wdir='C:/Users/hk/Desktop/FF/nfl-fantasy-football-master/Data Analysis')
Traceback (most recent call last):

  File "C:\Users\hk\Desktop\FF\nfl-fantasy-football-master\Data Analysis\Data Transformations.py", line 15, in <module>
    with open('.\auth\oauth2yahoo.json') as json_yahoo_file:

OSError: [Errno 22] Invalid argument: '.\x07uth\\oauth2yahoo.json' 

```
I tried looking up the Errno but didn't seem to return anything useful.

Any tips on how to resolve are much appreciated!

Thanks,
Hargobind

**Comment by bbenbenek** [comment]
Not sure if you edited the line containing `with open('.\auth\oauth2yahoo.json')`, but the slashes need to be forward, not backward.
